[package]
name = "laibrary"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.2.6"

[dependencies]
toml = "0.8.19"
tree-sitter = "0.24.6"
tree-sitter-rust = "0.23.2"
walkdir = "2.4.0"

[dev-dependencies]
tempfile = "3.10.0"
